# This file may be used to create an environment using:
# $ conda env create -f environment.yml
# platform: linux-64
name: HAMLET
channels:
  - bioconda
  - conda-forge
dependencies:
  - crimson=1.1.0
  - peppy=0.35
  - python<3.11
  - pytest-workflow=1.6.0
  - snakemake-minimal=7.15
  - snakefmt=0.6.1
  - tabulate=0.8.10
