# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
name: HAMLET
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
 - pytest-workflow
 - python=3.6
 - snakemake=5.9
